import type { AppState, Profile, Project, User } from "@/types";
import { computeCompleteness } from "@/lib/completeness";
import { hashPassword, nowIso } from "@/lib/utils";

const DEMO_PASSWORD = "Campus2026!";

async function user(
  id: string,
  email: string,
  role: User["role"],
  createdAt: string
): Promise<User> {
  return {
    id,
    email,
    passwordHash: await hashPassword(DEMO_PASSWORD),
    role,
    emailVerified: true,
    status: "active",
    lastActiveAt: nowIso(),
    createdAt,
    updatedAt: createdAt,
  };
}

function profile(p: Omit<Profile, "id" | "profileCompleteness" | "createdAt" | "updatedAt"> & { createdAt: string }): Profile {
  const full: Profile = {
    id: `prof-${p.userId}`,
    profileCompleteness: 0,
    updatedAt: p.createdAt,
    ...p,
  };
  full.profileCompleteness = computeCompleteness(full);
  return full;
}

export const DEMO_CREDENTIALS = {
  password: DEMO_PASSWORD,
  student: "rahul@dtu.ac.in",
  faculty: "priya@iitd.ac.in",
  admin: "admin@synaptra.edu",
  owner: "arjun@iitb.ac.in",
};

export async function createSeed(): Promise<AppState> {
  const t = (days: number) => new Date(Date.now() - days * 86400000).toISOString();

  const users = await Promise.all([
    user("u-admin", DEMO_CREDENTIALS.admin, "admin", t(40)),
    user("u-rahul", DEMO_CREDENTIALS.student, "student", t(20)),
    user("u-priya", DEMO_CREDENTIALS.faculty, "faculty", t(28)),
    user("u-arjun", DEMO_CREDENTIALS.owner, "student", t(18)),
    user("u-divya", "divya@uohyd.ac.in", "student", t(16)),
    user("u-karthik", "karthik@nitt.edu", "student", t(14)),
    user("u-sneha", "sneha@iisc.ac.in", "student", t(12)),
    user("u-meera", "meera@annauniv.edu", "faculty", t(22)),
  ]);

  const profiles: Profile[] = [
    profile({
      userId: "u-admin",
      fullName: "Platform Administrator",
      institution: "SYNAPTRA",
      department: "Academic Technology",
      bio: "Moderates the research collaboration platform.",
      visibility: "private",
      skills: [],
      interests: [],
      programmingLanguages: [],
      pastProjects: [],
      internships: [],
      certifications: [],
      publications: [],
      githubConnected: false,
      preferredRoles: [],
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: false,
      openToMentoring: false,
      preferredProjectTypes: [],
      createdAt: t(40),
    }),
    profile({
      userId: "u-rahul",
      fullName: "Rahul Mehta",
      institution: "Delhi Technological University",
      department: "Computer Science and Engineering",
      bio: "Final-year student focused on applied machine learning and computer vision.",
      visibility: "public",
      skills: [
        { skill: "Python", proficiency: "advanced" },
        { skill: "Machine Learning", proficiency: "advanced" },
        { skill: "Computer Vision", proficiency: "intermediate" },
        { skill: "Deep Learning", proficiency: "intermediate" },
        { skill: "Git", proficiency: "intermediate" },
      ],
      interests: ["Machine Learning", "Computer Vision", "Agriculture Tech", "Healthcare AI"],
      programmingLanguages: ["Python", "JavaScript"],
      pastProjects: [
        {
          id: "pp-1",
          title: "Campus Attendance Vision System",
          description: "CNN-based face recognition attendance prototype using Python.",
          year: 2025,
        },
      ],
      internships: [
        {
          id: "in-1",
          organization: "AgriSense Labs",
          role: "ML Intern",
          description: "Assisted with crop-image classification pipelines.",
        },
      ],
      certifications: [{ id: "c-1", name: "Deep Learning Specialization", issuer: "Coursera", year: 2025 }],
      publications: [],
      githubUsername: "octocat",
      githubConnected: true,
      linkedinUrl: "https://linkedin.com/in/example",
      availabilityHours: 12,
      preferredRoles: ["Machine Learning Engineer", "Data Scientist"],
      preferredTeamSize: 5,
      degreeProgram: "B.Tech",
      academicYear: 4,
      graduationYear: 2026,
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: true,
      openToMentoring: false,
      preferredProjectTypes: ["Final-Year Project", "Hackathon", "Research Project"],
      createdAt: t(20),
    }),
    profile({
      userId: "u-priya",
      fullName: "Dr. Priya Sharma",
      institution: "Indian Institute of Technology Delhi",
      department: "Computer Science and Engineering",
      bio: "Assistant Professor working on healthcare imaging and responsible AI.",
      visibility: "public",
      skills: [
        { skill: "Machine Learning", proficiency: "advanced" },
        { skill: "Computer Vision", proficiency: "advanced" },
        { skill: "Research Writing", proficiency: "advanced" },
        { skill: "Literature Review", proficiency: "advanced" },
      ],
      interests: ["Healthcare AI", "Computer Vision", "Responsible AI", "Machine Learning"],
      programmingLanguages: ["Python"],
      pastProjects: [],
      internships: [],
      certifications: [],
      publications: [
        {
          id: "pub-1",
          title: "Weakly Supervised Screening for Diabetic Retinopathy",
          venue: "MICCAI Workshop",
          year: 2024,
        },
      ],
      githubConnected: false,
      availabilityHours: 6,
      preferredRoles: ["Faculty/Mentor", "Researcher"],
      designation: "Assistant Professor",
      subjectsTaught: ["Machine Learning", "Computer Vision"],
      teachingAreas: ["AI for Health"],
      academicExperience: 8,
      researchExperience: 10,
      researchDomains: ["Healthcare AI", "Computer Vision"],
      expertise: ["Medical imaging", "Weak supervision"],
      openToCollaboration: true,
      openToMentoring: true,
      preferredProjectTypes: ["Faculty-Led Research", "Publication-Oriented"],
      googleScholar: "https://scholar.google.com",
      createdAt: t(28),
    }),
    profile({
      userId: "u-arjun",
      fullName: "Arjun Nair",
      institution: "Indian Institute of Technology Bombay",
      department: "Computer Science and Engineering",
      bio: "Builds product-oriented research teams for hackathons and applied AI.",
      visibility: "public",
      skills: [
        { skill: "Python", proficiency: "advanced" },
        { skill: "Backend", proficiency: "advanced" },
        { skill: "Frontend", proficiency: "intermediate" },
        { skill: "Machine Learning", proficiency: "intermediate" },
      ],
      interests: ["Software Engineering", "Machine Learning", "Healthcare AI"],
      programmingLanguages: ["Python", "TypeScript"],
      pastProjects: [
        {
          id: "pp-2",
          title: "Clinic Queue Optimizer",
          description: "Backend service for hospital wait-time prediction.",
          year: 2025,
        },
      ],
      internships: [],
      certifications: [],
      publications: [],
      githubUsername: "github",
      githubConnected: true,
      availabilityHours: 14,
      preferredRoles: ["Project Lead", "Backend Developer"],
      degreeProgram: "B.Tech",
      academicYear: 3,
      graduationYear: 2027,
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: true,
      openToMentoring: false,
      preferredProjectTypes: ["Hackathon", "Innovation Project"],
      createdAt: t(18),
    }),
    profile({
      userId: "u-divya",
      fullName: "Divya Iyer",
      institution: "University of Hyderabad",
      department: "English and Humanities",
      bio: "Research writer focused on publication-quality documentation for technical teams.",
      visibility: "public",
      skills: [
        { skill: "Research Writing", proficiency: "advanced" },
        { skill: "Literature Review", proficiency: "advanced" },
        { skill: "Academic Publishing", proficiency: "intermediate" },
        { skill: "Survey Design", proficiency: "intermediate" },
      ],
      interests: ["Digital Humanities", "Education Technology", "Responsible AI"],
      programmingLanguages: [],
      pastProjects: [
        {
          id: "pp-3",
          title: "Annotation Guide for NLP Corpora",
          description: "Wrote methodology and related-work sections for a Hindi NLP corpus paper.",
          year: 2025,
        },
      ],
      internships: [],
      certifications: [],
      publications: [],
      githubConnected: false,
      availabilityHours: 10,
      preferredRoles: ["Research Writer", "Researcher"],
      degreeProgram: "M.Sc",
      academicYear: 2,
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: true,
      openToMentoring: false,
      preferredProjectTypes: ["Publication-Oriented", "Research Project"],
      createdAt: t(16),
    }),
    profile({
      userId: "u-karthik",
      fullName: "Karthik Rao",
      institution: "National Institute of Technology Trichy",
      department: "Information Technology",
      bio: "Frontend engineer interested in research tools and accessible interfaces.",
      visibility: "public",
      skills: [
        { skill: "Frontend", proficiency: "advanced" },
        { skill: "TypeScript", proficiency: "advanced" },
        { skill: "UI/UX", proficiency: "intermediate" },
        { skill: "JavaScript", proficiency: "advanced" },
      ],
      interests: ["Human-Computer Interaction", "Education Technology", "Software Engineering"],
      programmingLanguages: ["TypeScript", "JavaScript"],
      pastProjects: [],
      internships: [],
      certifications: [],
      publications: [],
      githubConnected: true,
      githubUsername: "torvalds",
      availabilityHours: 8,
      preferredRoles: ["Frontend Developer", "UI/UX Designer"],
      degreeProgram: "B.Tech",
      academicYear: 3,
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: true,
      openToMentoring: false,
      preferredProjectTypes: ["Open-Source", "Academic Project"],
      createdAt: t(14),
    }),
    profile({
      userId: "u-sneha",
      fullName: "Sneha Patel",
      institution: "Indian Institute of Science Bangalore",
      department: "Data Science",
      bio: "Works on applied NLP and multilingual language technologies.",
      visibility: "public",
      skills: [
        { skill: "Natural Language Processing", proficiency: "advanced" },
        { skill: "Python", proficiency: "advanced" },
        { skill: "Machine Learning", proficiency: "advanced" },
        { skill: "Data Science", proficiency: "intermediate" },
      ],
      interests: ["Natural Language Processing", "Artificial Intelligence", "Education Technology"],
      programmingLanguages: ["Python"],
      pastProjects: [
        {
          id: "pp-4",
          title: "Code-mixed Sentiment Benchmark",
          description: "Built evaluation splits for Hindi-English social media text.",
          year: 2025,
        },
      ],
      internships: [],
      certifications: [],
      publications: [],
      githubConnected: false,
      availabilityHours: 9,
      preferredRoles: ["Machine Learning Engineer", "Researcher"],
      degreeProgram: "M.Tech",
      academicYear: 2,
      subjectsTaught: [],
      teachingAreas: [],
      researchDomains: [],
      expertise: [],
      openToCollaboration: true,
      openToMentoring: false,
      preferredProjectTypes: ["Research Project", "Publication-Oriented"],
      createdAt: t(12),
    }),
    profile({
      userId: "u-meera",
      fullName: "Dr. Meera Krishnan",
      institution: "Anna University",
      department: "Computer Science and Engineering",
      bio: "Faculty mentor for undergraduate research in NLP and education technology.",
      visibility: "public",
      skills: [
        { skill: "Natural Language Processing", proficiency: "advanced" },
        { skill: "Research Writing", proficiency: "advanced" },
        { skill: "Literature Review", proficiency: "advanced" },
      ],
      interests: ["Natural Language Processing", "Education Technology", "Responsible AI"],
      programmingLanguages: [],
      pastProjects: [],
      internships: [],
      certifications: [],
      publications: [
        {
          id: "pub-2",
          title: "Low-resource Morphological Analysis for Indian Languages",
          venue: "LREC",
          year: 2023,
        },
      ],
      githubConnected: false,
      preferredRoles: ["Faculty/Mentor"],
      designation: "Associate Professor",
      subjectsTaught: ["NLP", "Compiler Design"],
      teachingAreas: ["Language technologies"],
      academicExperience: 14,
      researchExperience: 16,
      researchDomains: ["Natural Language Processing"],
      expertise: ["Low-resource NLP"],
      openToCollaboration: true,
      openToMentoring: true,
      preferredProjectTypes: ["Faculty-Led Research"],
      createdAt: t(22),
    }),
  ];

  const plantRoles = [
    { id: "r-plant-ml", name: "Machine Learning Engineer", description: "Trains plant-disease models.", requiredSkills: ["Python", "Computer Vision"], openings: 1 },
    { id: "r-plant-fe", name: "Frontend Developer", description: "Builds the field-tech interface.", requiredSkills: ["Frontend"], openings: 1 },
    { id: "r-plant-wr", name: "Research Writer", description: "Documents methods and results.", requiredSkills: ["Research Writing"], openings: 1 },
  ];
  const healthRoles = [
    { id: "r-h-ds", name: "Data Scientist", description: "Evaluates screening models.", requiredSkills: ["Data Science", "Machine Learning"], openings: 1 },
    { id: "r-h-ml", name: "Machine Learning Engineer", description: "Implements imaging pipelines.", requiredSkills: ["Computer Vision"], openings: 1 },
    { id: "r-h-wr", name: "Research Writer", description: "Prepares publication drafts.", requiredSkills: ["Research Writing"], openings: 1 },
  ];
  const hindiRoles = [
    { id: "r-hi-nlp", name: "Machine Learning Engineer", description: "Builds Hindi NLP models.", requiredSkills: ["Natural Language Processing"], openings: 2 },
    { id: "r-hi-wr", name: "Research Writer", description: "Corpus documentation and paper writing.", requiredSkills: ["Research Writing"], openings: 1 },
  ];
  const hackRoles = [
    { id: "r-hk-lead", name: "Project Lead", description: "Owns delivery for the 36-hour sprint.", requiredSkills: ["Git"], openings: 1 },
    { id: "r-hk-be", name: "Backend Developer", description: "APIs and data services.", requiredSkills: ["Backend"], openings: 1 },
    { id: "r-hk-fe", name: "Frontend Developer", description: "Demo interface.", requiredSkills: ["Frontend"], openings: 1 },
    { id: "r-hk-ml", name: "Machine Learning Engineer", description: "Lightweight inference.", requiredSkills: ["Machine Learning"], openings: 1 },
    { id: "r-hk-ds", name: "Data Scientist", description: "Evaluation and metrics.", requiredSkills: ["Data Science"], openings: 1 },
  ];

  const projects: Project[] = [
    {
      id: "p-plant",
      ownerId: "u-arjun",
      title: "AI-Based Plant Disease Detection",
      shortDescription: "A computer-vision system that identifies crop leaf diseases from field photographs to support early agricultural intervention.",
      detailedDescription: "The project will collect a labelled leaf-image dataset, train a compact CNN, and deploy a mobile-friendly demo for extension workers. Emphasis is on explainable predictions and careful evaluation, not on claiming clinical-grade accuracy.",
      problemStatement: "Farmers often detect crop disease too late because expert inspection does not scale.",
      objectives: ["Build a labelled dataset", "Train a baseline CNN", "Publish an evaluation report"],
      domains: ["Agriculture", "Computer Vision"],
      interests: ["Agriculture Tech", "Machine Learning", "Computer Vision"],
      requiredSkills: ["Python", "Machine Learning", "Computer Vision", "Frontend", "Research Writing"],
      roles: plantRoles,
      teamMin: 3,
      teamMax: 5,
      duration: "4 months",
      difficulty: "intermediate",
      type: "Final-Year Project",
      visibility: "public",
      deadline: new Date(Date.now() + 21 * 86400000).toISOString(),
      expectedOutcomes: "Working prototype and technical report",
      mentorRequired: true,
      githubRequired: true,
      tags: ["vision", "agriculture"],
      status: "open",
      createdAt: t(10),
      updatedAt: t(2),
    },
    {
      id: "p-health",
      ownerId: "u-priya",
      title: "Healthcare Imaging Screening Assist",
      shortDescription: "Faculty-led study exploring weakly supervised screening models for retinal images, with a student research team.",
      detailedDescription: "Students will reproduce a baseline, curate evaluation splits, and document failure modes. Clinical claims are out of scope. The work is intended as a methods-and-limitations study.",
      problemStatement: "Screening pipelines overstate performance when evaluation is poorly designed.",
      objectives: ["Reproduce a baseline", "Document failure cases", "Draft a workshop paper"],
      domains: ["Healthcare", "Computer Vision"],
      interests: ["Healthcare AI", "Responsible AI", "Computer Vision"],
      requiredSkills: ["Python", "Computer Vision", "Research Writing", "Literature Review"],
      roles: healthRoles,
      teamMin: 3,
      teamMax: 4,
      duration: "6 months",
      difficulty: "advanced",
      type: "Faculty-Led Research",
      visibility: "public",
      deadline: new Date(Date.now() + 40 * 86400000).toISOString(),
      mentorRequired: false,
      githubRequired: false,
      tags: ["health", "vision"],
      status: "open",
      createdAt: t(12),
      updatedAt: t(3),
    },
    {
      id: "p-hindi",
      ownerId: "u-meera",
      title: "NLP Resources for Hindi",
      shortDescription: "Building carefully documented Hindi language resources and baseline models for academic reuse.",
      detailedDescription: "The team will compile a small, well-documented dataset, write annotation guidelines, and train a baseline classifier. Publication is a goal, not a guarantee.",
      objectives: ["Annotation guidelines", "Baseline model", "Reproducible split"],
      domains: ["Natural Language Processing"],
      interests: ["Natural Language Processing", "Education Technology"],
      requiredSkills: ["Natural Language Processing", "Python", "Research Writing"],
      roles: hindiRoles,
      teamMin: 2,
      teamMax: 4,
      duration: "5 months",
      difficulty: "intermediate",
      type: "Publication-Oriented",
      visibility: "restricted",
      deadline: new Date(Date.now() + 30 * 86400000).toISOString(),
      mentorRequired: false,
      githubRequired: false,
      tags: ["nlp", "hindi"],
      status: "open",
      createdAt: t(8),
      updatedAt: t(1),
    },
    {
      id: "p-hack",
      ownerId: "u-arjun",
      title: "Campus Health Hackathon Team",
      shortDescription: "A five-person team forming for a 36-hour hackathon on student wellness analytics with a working demo.",
      detailedDescription: "We need complementary roles: lead, backend, frontend, ML, and evaluation. The demo must run locally without paid APIs.",
      objectives: ["Working demo", "Pitch deck", "Evaluation snapshot"],
      domains: ["Healthcare", "Software Engineering"],
      interests: ["Healthcare AI", "Software Engineering"],
      requiredSkills: ["Backend", "Frontend", "Machine Learning", "Data Science"],
      roles: hackRoles,
      teamMin: 5,
      teamMax: 5,
      duration: "3 weeks",
      difficulty: "beginner",
      type: "Hackathon",
      visibility: "public",
      deadline: new Date(Date.now() + 9 * 86400000).toISOString(),
      mentorRequired: false,
      githubRequired: true,
      tags: ["hackathon"],
      status: "open",
      createdAt: t(4),
      updatedAt: t(1),
    },
  ];

  return {
    users,
    profiles,
    projects,
    members: [
      { id: "m-plant-o", projectId: "p-plant", userId: "u-arjun", systemRole: "owner", status: "active", createdAt: t(10) },
      { id: "m-health-o", projectId: "p-health", userId: "u-priya", systemRole: "owner", status: "active", createdAt: t(12) },
      { id: "m-health-m", projectId: "p-health", userId: "u-priya", systemRole: "mentor", status: "active", createdAt: t(12) },
      { id: "m-hindi-o", projectId: "p-hindi", userId: "u-meera", systemRole: "owner", status: "active", createdAt: t(8) },
      { id: "m-hack-o", projectId: "p-hack", userId: "u-arjun", systemRole: "owner", status: "active", createdAt: t(4) },
      { id: "m-plant-r", projectId: "p-plant", userId: "u-rahul", systemRole: "member", roleId: "r-plant-ml", status: "active", createdAt: t(3) },
    ],
    joinRequests: [
      {
        id: "jr-health-rahul",
        projectId: "p-health",
        applicantId: "u-rahul",
        selectedRoleId: "r-h-ml",
        motivation:
          "I want to apply computer vision work from my plant-disease prototype to a more carefully evaluated healthcare screening study, with explicit limits on clinical claims.",
        relevantExperience: "CNN attendance prototype and AgriSense internship on image classification.",
        status: "pending",
        createdAt: t(3),
        updatedAt: t(3),
      },
    ],
    invitations: [],
    detailsRequests: [],
    mentorshipRequests: [
      {
        id: "mr-1",
        projectId: "p-plant",
        facultyId: "u-priya",
        message: "Happy to mentor on evaluation design and avoiding overstated accuracy claims.",
        status: "pending",
        createdAt: t(2),
      },
    ],
    tasks: [
      {
        id: "t-1",
        projectId: "p-plant",
        title: "Collect 400 labelled leaf images",
        description: "Balance healthy vs diseased classes.",
        assignedTo: "u-rahul",
        priority: "high",
        status: "in_progress",
        createdBy: "u-arjun",
        createdAt: t(3),
        updatedAt: t(1),
        deadline: new Date(Date.now() + 5 * 86400000).toISOString(),
      },
      {
        id: "t-2",
        projectId: "p-plant",
        title: "Draft dataset card",
        priority: "medium",
        status: "todo",
        createdBy: "u-arjun",
        createdAt: t(3),
        updatedAt: t(3),
      },
      {
        id: "t-3",
        projectId: "p-plant",
        title: "Baseline ResNet-18 training",
        assignedTo: "u-rahul",
        priority: "high",
        status: "review",
        createdBy: "u-arjun",
        createdAt: t(2),
        updatedAt: t(1),
      },
    ],
    taskComments: [],
    milestones: [
      {
        id: "ms-1",
        projectId: "p-plant",
        title: "Dataset freeze",
        description: "No further labelling changes without versioning.",
        dueDate: new Date(Date.now() + 12 * 86400000).toISOString(),
        completed: false,
        createdAt: t(3),
      },
    ],
    activity: [
      {
        id: "a-1",
        projectId: "p-plant",
        userId: "u-arjun",
        type: "member",
        message: "Rahul Mehta joined as Machine Learning Engineer.",
        createdAt: t(3),
      },
      {
        id: "a-2",
        projectId: "p-plant",
        userId: "u-rahul",
        type: "task",
        message: "Moved “Baseline ResNet-18 training” to Review.",
        createdAt: t(1),
      },
    ],
    notifications: [
      {
        id: "n-1",
        userId: "u-rahul",
        type: "application_accepted",
        title: "Application accepted",
        message: "You were accepted to AI-Based Plant Disease Detection.",
        link: "/room/p-plant",
        read: false,
        createdAt: t(3),
      },
      {
        id: "n-2",
        userId: "u-priya",
        type: "join_request",
        title: "New join request",
        message: "Rahul Mehta applied to Healthcare Imaging Screening Assist.",
        link: "/room/p-health?tab=applications",
        read: false,
        createdAt: t(3),
      },
      {
        id: "n-3",
        userId: "u-arjun",
        type: "mentorship_request",
        title: "Mentorship request",
        message: "Dr. Priya Sharma requested to mentor AI-Based Plant Disease Detection.",
        link: "/room/p-plant?tab=team",
        read: false,
        createdAt: t(2),
      },
    ],
    notes: [
      {
        id: "note-1",
        projectId: "p-plant",
        title: "Related work: PlantVillage",
        content: "PlantVillage remains a common baseline dataset; field photographs are more difficult than lab images.",
        category: "literature",
        tags: ["dataset"],
        createdBy: "u-rahul",
        createdAt: t(2),
        updatedAt: t(2),
      },
    ],
    references: [],
    experiments: [],
    meetings: [],
    datasets: [],
    documents: [],
    discussions: [
      {
        id: "d-1",
        projectId: "p-plant",
        title: "Evaluation protocol",
        body: "We should report per-class recall and avoid a single accuracy number.",
        createdBy: "u-arjun",
        createdAt: t(2),
      },
    ],
    replies: [],
    reports: [],
    auditLogs: [],
    aiLogs: [],
    sessionUserId: null,
  };
}
